language: node_js

services:
    - 'docker'

node_js:
  - 14.15.0

  
cache:
    directories:
        - "node_modules"

after_success:
    - docker build -t requisitions .
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

before_deploy:
    - docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD" docker.io ;
    - docker tag requisitions $DOCKER_USERNAME/requisitions:latest

deploy:
    provider: script
    script: docker push $DOCKER_USERNAME/requisitions:latest ;

notifications:
    email: false

